# Generated by Django 5.1.6 on 2025-03-03 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('phone_1', models.CharField(max_length=15)),
                ('phone_2', models.CharField(blank=True, max_length=15, null=True)),
                ('inter_group', models.CharField(blank=True, max_length=100, null=True)),
                ('inter_marks', models.IntegerField(blank=True, null=True)),
                ('exam_rank', models.CharField(blank=True, max_length=50, null=True)),
                ('call_1_status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('not_answered', 'Not Answered'), ('wrong_number', 'Wrong Number')], default='pending', max_length=20)),
                ('call_2_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('answered', 'Answered'), ('not_answered', 'Not Answered'), ('wrong_number', 'Wrong Number')], default='pending', max_length=20, null=True)),
                ('call_3_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('answered', 'Answered'), ('not_answered', 'Not Answered'), ('wrong_number', 'Wrong Number')], default='pending', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
