# Generated by Django 5.1.6 on 2025-03-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentcall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcall',
            name='inter_group',
            field=models.CharField(blank=True, choices=[('MPC', 'MPC'), ('BiPC', 'BiPC'), ('CEC', 'CEC'), ('MEC', 'MEC'), ('HEC', 'HEC'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
