# Generated by Django 5.1.6 on 2025-03-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_studentcall_inter_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcall',
            name='call_1_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('not_answered', 'Not Answered'), ('wrong_number', 'Wrong Number'), ('interested', 'Interested'), ('not_interested', 'Not Interested')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentcall',
            name='call_2_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('answered', 'Answered'), ('not_answered', 'Not Answered'), ('wrong_number', 'Wrong Number'), ('interested', 'Interested'), ('not_interested', 'Not Interested')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentcall',
            name='call_3_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('answered', 'Answered'), ('not_answered', 'Not Answered'), ('wrong_number', 'Wrong Number'), ('interested', 'Interested'), ('not_interested', 'Not Interested')], default='pending', max_length=20, null=True),
        ),
    ]
