# Generated by Django 5.1.6 on 2025-03-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_studentcall_call_1_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcall',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcall',
            name='rmarks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcall',
            name='status',
            field=models.CharField(choices=[('NI', 'Not Interested'), ('I', 'Interested'), ('WD', 'Willing to Degree'), ('WE', 'Willing to Engineering'), ('ND', 'Not Decided'), ('J', 'Joined')], default='ND', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentcall',
            name='call_1_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Answered'), ('NA', 'Not Answered'), ('WN', 'Wrong Number'), ('I', 'Interested'), ('NI', 'Not Interested')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentcall',
            name='call_2_status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Answered'), ('NA', 'Not Answered'), ('WN', 'Wrong Number'), ('I', 'Interested'), ('NI', 'Not Interested')], default='P', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentcall',
            name='call_3_status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Answered'), ('NA', 'Not Answered'), ('WN', 'Wrong Number'), ('I', 'Interested'), ('NI', 'Not Interested')], default='P', max_length=2, null=True),
        ),
    ]
