# Generated by Django 5.1.6 on 2025-03-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studentcall_comments_studentcall_rmarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcall',
            name='call_2_status',
        ),
        migrations.RemoveField(
            model_name='studentcall',
            name='call_3_status',
        ),
    ]
