# Generated by Django 5.1.6 on 2025-03-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_studentcall_call_2_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcall',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentcall',
            name='college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentcall',
            name='status',
            field=models.CharField(choices=[('NI', 'Not Interested'), ('WD', 'Willing to Degree'), ('WE', 'Willing to Engineering'), ('ND', 'Not Decided'), ('J', 'Joined')], default='ND', max_length=2),
        ),
    ]
